my_project:
  outputs:
    dev:
      dataset: cafe
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: australia-southeast1
      method: oauth
      priority: interactive
      project: jr-data-training
      threads: 4
      type: bigquery
  target: dev
user:
  outputs:
    default:
      dataset: dbt_cafeanalytics
      location: australia-southeast1
      method: service-account
      project: jr-data-training
      type: bigquery
  target: default
