version: 2

sources:
    - name: cafe_raw
      description: Cafe's online sales raw data.
      database: jr-data-training
      schema: cafe
      tables:
        - name: cafe
          identifier: cafe-sales
          description: Sales data with attributes in raw schema.
          columns:
            - name: order_id
              tests:
                - unique
                - not_null
            - name: customer_id
              tests:
                - not_null
            - name: date_created
              tests:
                - not_null